"""add thumbnails to story

Revision ID: 2022_10_05_1642
Revises: 2022_10_04_2149
Create Date: 2022-10-05 16:42:53.625904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2022_10_05_1642'
down_revision = '2022_10_04_2149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('thumbnail', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'thumbnail')
    # ### end Alembic commands ###
