"""add recipe step num

Revision ID: 2022_08_30_1717
Revises: 2022_08_24_1703
Create Date: 2022-08-30 17:17:44.950199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2022_08_30_1717'
down_revision = '2022_08_24_1703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_steps', sa.Column('step_num', sa.Integer(), nullable=False))
    op.drop_constraint('recipes_user_id_fkey', 'recipes', type_='foreignkey')
    op.create_foreign_key(None, 'recipes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.create_foreign_key('recipes_user_id_fkey', 'recipes', 'users', ['user_id'], ['id'])
    op.drop_column('recipe_steps', 'step_num')
    # ### end Alembic commands ###
