"""add_foreign_keys

Revision ID: 2022_08_23_1516
Revises: 2022_08_23_1323
Create Date: 2022-08-23 15:16:25.408477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2022_08_23_1516'
down_revision = '2022_08_23_1323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
