"""add stories

Revision ID: 2022_10_03_1721
Revises: 2022_10_02_1644
Create Date: 2022-10-03 17:21:54.022699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2022_10_03_1721'
down_revision = '2022_10_02_1644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('story_item',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('story_id', sa.Integer(), nullable=True),
                    sa.Column('image', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story_item')
    op.drop_table('story')
    # ### end Alembic commands ###
