"""add ingredeints groups

Revision ID: 2022_08_23_2110
Revises: 2022_08_23_1516
Create Date: 2022-08-23 21:10:33.750198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2022_08_23_2110'
down_revision = '2022_08_23_1516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assoc_ingredients_groups',
    sa.Column('ingredients_group_id', sa.Integer(), nullable=True),
    sa.Column('ingredients_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredients_group_id'], ['ingredients_groups.id'], ),
    sa.ForeignKeyConstraint(['ingredients_id'], ['ingredients.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assoc_ingredients_groups')
    op.drop_table('ingredients_groups')
    # ### end Alembic commands ###
