"""update groups

Revision ID: 2022_08_24_1655
Revises: 2022_08_24_1614
Create Date: 2022-08-24 16:55:20.231086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2022_08_24_1655'
down_revision = '2022_08_24_1614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ingredients', 'ingredients_groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.drop_column('ingredients', 'group_id')
    # ### end Alembic commands ###
