"""remove unused parameter from user model

Revision ID: 2022_10_25_1207
Revises: 2022_10_05_1642
Create Date: 2022-10-25 12:07:16.860512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2022_10_25_1207'
down_revision = '2022_10_05_1642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'jwt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('jwt', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
