"""change groups

Revision ID: 2022_08_24_1703
Revises: 2022_08_24_1655
Create Date: 2022-08-24 17:03:40.964247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2022_08_24_1703'
down_revision = '2022_08_24_1655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ingredients_group_id_fkey', 'ingredients', type_='foreignkey')
    op.drop_column('ingredients', 'group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('ingredients_group_id_fkey', 'ingredients', 'ingredients_groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
