"""update recipes

Revision ID: 2022_08_24_1613
Revises: 2022_08_23_2110
Create Date: 2022-08-24 16:13:06.504464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2022_08_24_1613'
down_revision = '2022_08_23_2110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('time', sa.Integer(), nullable=False))
    op.add_column('recipes', sa.Column('complexity', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'complexity')
    op.drop_column('recipes', 'time')
    # ### end Alembic commands ###
