"""add group expiration time

Revision ID: 2023_04_11_0038
Revises: 2022_10_25_1207
Create Date: 2023-04-11 00:38:18.396087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2023_04_11_0038'
down_revision = '2022_10_25_1207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assoc_users_groups', sa.Column('expiration_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assoc_users_groups', 'expiration_time')
    # ### end Alembic commands ###
