"""add compilation position

Revision ID: 2023_05_11_1310
Revises: 2023_04_11_1929
Create Date: 2023-05-11 13:10:59.839462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2023_05_11_1310'
down_revision = '2023_04_11_1929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_compilations', sa.Column('position', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_compilations', 'position')
    # ### end Alembic commands ###
